In [35]:
!pip install -i https://test.pypi.org/simple/ FINITO-FEM-TOOLBOX
import numpy as np

Looking in indexes: https://test.pypi.org/simple/
Requirement already satisfied: FINITO-FEM-TOOLBOX in /usr/local/lib/python3.7/dist-packages (0.0.1)

In [44]:
F_I =5
F_II =10
E_C =3.1e6
E_CV =E_C*0.4
E_CP =E_C*0.8
A_V =0.2*0.4
A_P =0.3*0.5
I_V =0.2*0.4**3/12
I_P =0.3*0.5**3/12


DADOS={
'F_I':F_I,
'F_II':F_II,
'E_C':E_C,
'E_CV':E_CV,
'E_CP':E_CP,
'A_V':A_V,
'A_P':A_P,
'I_V':I_V,
'I_P':I_P
}

In [45]:
from FINITO_FEM_TOOLBOX import MEF1D
 
FRAME_00 = {
                "TYPE_ELEMENT": 0,
                "TYPE_SOLUTION": 0,
                "N_NODES": 128,
                "N_MATERIALS": 2,
                "N_SECTIONS": 2,
                "N_ELEMENTS": 136,
                "N_DOFPRESCRIPTIONS": 12,
                "N_DOFLOADED": 124,
                "N_DOFSPRINGS": 0,
                "COORDINATES": #X,Y
                np.array([
                [0,0],
                [5,0],
                [10,0],
                [15,0],
                [0,3],
                [0.5,3],
                [1,3],
                [1.5,3],
                [2,3],
                [2.5,3],
                [3,3],
                [3.5,3],
                [4,3],
                [4.5,3],
                [5,3],
                [5.5,3],
                [6,3],
                [6.5,3],
                [7,3],
                [7.5,3],
                [8,3],
                [8.5,3],
                [9,3],
                [9.5,3],
                [10,3],
                [10.5,3],
                [11,3],
                [11.5,3],
                [12,3],
                [12.5,3],
                [13,3],
                [13.5,3],
                [14,3],
                [14.5,3],
                [15,3],
                [0,6],
                [0.5,6],
                [1,6],
                [1.5,6],
                [2,6],
                [2.5,6],
                [3,6],
                [3.5,6],
                [4,6],
                [4.5,6],
                [5,6],
                [5.5,6],
                [6,6],
                [6.5,6],
                [7,6],
                [7.5,6],
                [8,6],
                [8.5,6],
                [9,6],
                [9.5,6],
                [10,6],
                [10.5,6],
                [11,6],
                [11.5,6],
                [12,6],
                [12.5,6],
                [13,6],
                [13.5,6],
                [14,6],
                [14.5,6],
                [15,6],
                [0,9],
                [0.5,9],
                [1,9],
                [1.5,9],
                [2,9],
                [2.5,9],
                [3,9],
                [3.5,9],
                [4,9],
                [4.5,9],
                [5,9],
                [5.5,9],
                [6,9],
                [6.5,9],
                [7,9],
                [7.5,9],
                [8,9],
                [8.5,9],
                [9,9],
                [9.5,9],
                [10,9],
                [10.5,9],
                [11,9],
                [11.5,9],
                [12,9],
                [12.5,9],
                [13,9],
                [13.5,9],
                [14,9],
                [14.5,9],
                [15,9],
                [0,12],
                [0.5,12],
                [1,12],
                [1.5,12],
                [2,12],
                [2.5,12],
                [3,12],
                [3.5,12],
                [4,12],
                [4.5,12],
                [5,12],
                [5.5,12],
                [6,12],
                [6.5,12],
                [7,12],
                [7.5,12],
                [8,12],
                [8.5,12],
                [9,12],
                [9.5,12],
                [10,12],
                [10.5,12],
                [11,12],
                [11.5,12],
                [12,12],
                [12.5,12],
                [13,12],
                [13.5,12],
                [14,12],
                [14.5,12],
                [15,12]]),

                "ELEMENTS": #NODE 1,NODE 2,MATERIAL ID,SECTION ID,HINGE ID NODE 1,HINGE ID NODE 2
                np.array([
                [0,4,1,1,0,0],
                [4,35,1,1,0,0],
                [35,66,1,1,0,0],
                [66,97,1,1,0,0],
                [1,14,1,1,0,0],
                [14,45,1,1,0,0],
                [45,76,1,1,0,0],
                [76,107,1,1,0,0],
                [2,24,1,1,0,0],
                [24,55,1,1,0,0],
                [55,86,1,1,0,0],
                [86,117,1,1,0,0],
                [3,34,1,1,0,0],
                [34,65,1,1,0,0],
                [65,96,1,1,0,0],
                [96,127,1,1,0,0],
                [4,5,0,0,0,0],
                [5,6,0,0,0,0],
                [6,7,0,0,0,0],
                [7,8,0,0,0,0],
                [8,9,0,0,0,0],
                [9,10,0,0,0,0],
                [10,11,0,0,0,0],
                [11,12,0,0,0,0],
                [12,13,0,0,0,0],
                [13,14,0,0,0,0],
                [14,15,0,0,0,0],
                [15,16,0,0,0,0],
                [16,17,0,0,0,0],
                [17,18,0,0,0,0],
                [18,19,0,0,0,0],
                [19,20,0,0,0,0],
                [20,21,0,0,0,0],
                [21,22,0,0,0,0],
                [22,23,0,0,0,0],
                [23,24,0,0,0,0],
                [24,25,0,0,0,0],
                [25,26,0,0,0,0],
                [26,27,0,0,0,0],
                [27,28,0,0,0,0],
                [28,29,0,0,0,0],
                [29,30,0,0,0,0],
                [30,31,0,0,0,0],
                [31,32,0,0,0,0],
                [32,33,0,0,0,0],
                [33,34,0,0,0,0],
                [35,36,0,0,0,0],
                [36,37,0,0,0,0],
                [37,38,0,0,0,0],
                [38,39,0,0,0,0],
                [39,40,0,0,0,0],
                [40,41,0,0,0,0],
                [41,42,0,0,0,0],
                [42,43,0,0,0,0],
                [43,44,0,0,0,0],
                [44,45,0,0,0,0],
                [45,46,0,0,0,0],
                [46,47,0,0,0,0],
                [47,48,0,0,0,0],
                [48,49,0,0,0,0],
                [49,50,0,0,0,0],
                [50,51,0,0,0,0],
                [51,52,0,0,0,0],
                [52,53,0,0,0,0],
                [53,54,0,0,0,0],
                [54,55,0,0,0,0],
                [55,56,0,0,0,0],
                [56,57,0,0,0,0],
                [57,58,0,0,0,0],
                [58,59,0,0,0,0],
                [59,60,0,0,0,0],
                [60,61,0,0,0,0],
                [61,62,0,0,0,0],
                [62,63,0,0,0,0],
                [63,64,0,0,0,0],
                [64,65,0,0,0,0],
                [66,67,0,0,0,0],
                [67,68,0,0,0,0],
                [68,69,0,0,0,0],
                [69,70,0,0,0,0],
                [70,71,0,0,0,0],
                [71,72,0,0,0,0],
                [72,73,0,0,0,0],
                [73,74,0,0,0,0],
                [74,75,0,0,0,0],
                [75,76,0,0,0,0],
                [76,77,0,0,0,0],
                [77,78,0,0,0,0],
                [78,79,0,0,0,0],
                [79,80,0,0,0,0],
                [80,81,0,0,0,0],
                [81,82,0,0,0,0],
                [82,83,0,0,0,0],
                [83,84,0,0,0,0],
                [84,85,0,0,0,0],
                [85,86,0,0,0,0],
                [86,87,0,0,0,0],
                [87,88,0,0,0,0],
                [88,89,0,0,0,0],
                [89,90,0,0,0,0],
                [90,91,0,0,0,0],
                [91,92,0,0,0,0],
                [92,93,0,0,0,0],
                [93,94,0,0,0,0],
                [94,95,0,0,0,0],
                [95,96,0,0,0,0],
                [97,98,0,0,0,0],
                [98,99,0,0,0,0],
                [99,100,0,0,0,0],
                [100,101,0,0,0,0],
                [101,102,0,0,0,0],
                [102,103,0,0,0,0],
                [103,104,0,0,0,0],
                [104,105,0,0,0,0],
                [105,106,0,0,0,0],
                [106,107,0,0,0,0],
                [107,108,0,0,0,0],
                [108,109,0,0,0,0],
                [109,110,0,0,0,0],
                [110,111,0,0,0,0],
                [111,112,0,0,0,0],
                [112,113,0,0,0,0],
                [113,114,0,0,0,0],
                [114,115,0,0,0,0],
                [115,116,0,0,0,0],
                [116,117,0,0,0,0],
                [117,118,0,0,0,0],
                [118,119,0,0,0,0],
                [119,120,0,0,0,0],
                [120,121,0,0,0,0],
                [121,122,0,0,0,0],
                [122,123,0,0,0,0],
                [123,124,0,0,0,0],
                [124,125,0,0,0,0],
                [125,126,0,0,0,0],
                [126,127,0,0,0,0]]),

                "MATERIALS": #YOUNG, POISSON,DENSITY, THERMAL COEFFICIENT
                np.array([[DADOS['E_CV'], 1, 1, 1], [DADOS['E_CP'], 1, 1, 1]]),
                "SECTIONS": #AREA, INERTIA 1, INERTIA 2, X GC,Y GC
                np.array([[DADOS['A_V'] , DADOS['I_V'], DADOS['I_V'], 0, 0],[DADOS['A_P'] , DADOS['I_P'], DADOS['I_P'], 0, 0]]),
                #np.array([[0.0450,0.000377,0.000377,0.075,0.15]]),
                "PRESCRIBED DISPLACEMENTS": #NODE,DIRECTION(X=0,Y=1,Z=2),VALUE
                np.array([
                [0,0,0],
                [0,1,0],
                [0,2,0],
                [1,0,0],
                [1,1,0],
                [1,2,0],
                [2,0,0],
                [2,1,0],
                [2,2,0],
                [3,0,0],
                [3,1,0],
                [3,2,0]]),
                "ELEMENT LOADS": None,
                "NODAL LOADS":  #NODE,DIRECTION(X=0,Y=1,Z=2),VALUE
                np.array([
                [4,1,-F_I],
                [5,1,-F_II],
                [6,1,-F_II],
                [7,1,-F_II],
                [8,1,-F_II],
                [9,1,-F_II],
                [10,1,-F_II],
                [11,1,-F_II],
                [12,1,-F_II],
                [13,1,-F_II],
                [14,1,-F_II],
                [15,1,-F_II],
                [16,1,-F_II],
                [17,1,-F_II],
                [18,1,-F_II],
                [19,1,-F_II],
                [20,1,-F_II],
                [21,1,-F_II],
                [22,1,-F_II],
                [23,1,-F_II],
                [24,1,-F_II],
                [25,1,-F_II],
                [26,1,-F_II],
                [27,1,-F_II],
                [28,1,-F_II],
                [29,1,-F_II],
                [30,1,-F_II],
                [31,1,-F_II],
                [32,1,-F_II],
                [33,1,-F_II],
                [34,1,-F_I],
                [35,1,-F_I],
                [36,1,-F_II],
                [37,1,-F_II],
                [38,1,-F_II],
                [39,1,-F_II],
                [40,1,-F_II],
                [41,1,-F_II],
                [42,1,-F_II],
                [43,1,-F_II],
                [44,1,-F_II],
                [45,1,-F_II],
                [46,1,-F_II],
                [47,1,-F_II],
                [48,1,-F_II],
                [49,1,-F_II],
                [50,1,-F_II],
                [51,1,-F_II],
                [52,1,-F_II],
                [53,1,-F_II],
                [54,1,-F_II],
                [55,1,-F_II],
                [56,1,-F_II],
                [57,1,-F_II],
                [58,1,-F_II],
                [59,1,-F_II],
                [60,1,-F_II],
                [61,1,-F_II],
                [62,1,-F_II],
                [63,1,-F_II],
                [64,1,-F_II],
                [65,1,-F_I],
                [66,1,-F_I],
                [67,1,-F_II],
                [68,1,-F_II],
                [69,1,-F_II],
                [70,1,-F_II],
                [71,1,-F_II],
                [72,1,-F_II],
                [73,1,-F_II],
                [74,1,-F_II],
                [75,1,-F_II],
                [76,1,-F_II],
                [77,1,-F_II],
                [78,1,-F_II],
                [79,1,-F_II],
                [80,1,-F_II],
                [81,1,-F_II],
                [82,1,-F_II],
                [83,1,-F_II],
                [84,1,-F_II],
                [85,1,-F_II],
                [86,1,-F_II],
                [87,1,-F_II],
                [88,1,-F_II],
                [89,1,-F_II],
                [90,1,-F_II],
                [91,1,-F_II],
                [92,1,-F_II],
                [93,1,-F_II],
                [94,1,-F_II],
                [95,1,-F_II],
                [96,1,-F_I],
                [97,1,-F_I],
                [98,1,-F_II],
                [99,1,-F_II],
                [100,1,-F_II],
                [101,1,-F_II],
                [102,1,-F_II],
                [103,1,-F_II],
                [104,1,-F_II],
                [105,1,-F_II],
                [106,1,-F_II],
                [107,1,-F_II],
                [108,1,-F_II],
                [109,1,-F_II],
                [110,1,-F_II],
                [111,1,-F_II],
                [112,1,-F_II],
                [113,1,-F_II],
                [114,1,-F_II],
                [115,1,-F_II],
                [116,1,-F_II],
                [117,1,-F_II],
                [118,1,-F_II],
                [119,1,-F_II],
                [120,1,-F_II],
                [121,1,-F_II],
                [122,1,-F_II],
                [123,1,-F_II],
                [124,1,-F_II],
                [125,1,-F_II],
                [126,1,-F_II],
                [127,1,-F_I]]),
            
                "SPRINGS": None}    

FRAME_00_RESULTS = MEF1D(DICTIONARY = FRAME_00)

In [46]:
# Output print
import pandas as pd
FRAME_00_RESULTS_0 = pd.DataFrame(data = FRAME_00_RESULTS[0])
FRAME_00_RESULTS_0.head(50)

      X           UX           UY  ...         V          M  ID_ELEMENT
0   0.0     0.000000     0.000000  ... -9.456106  10.003530           0
1   0.3 -1989.000000 -1989.000000  ... -9.456106   7.166698           0
2   0.6 -1989.000000 -1989.000000  ... -9.456106   4.329867           0
3   0.9 -1989.000000 -1989.000000  ... -9.456106   1.493035           0
4   1.2 -1989.000000 -1989.000000  ... -9.456106  -1.343797           0
5   1.5 -1989.000000 -1989.000000  ... -9.456106  -4.180628           0
6   1.8 -1989.000000 -1989.000000  ... -9.456106  -7.017460           0
7   2.1 -1989.000000 -1989.000000  ... -9.456106  -9.854292           0
8   2.4 -1989.000000 -1989.000000  ... -9.456106 -12.691123           0
9   2.7 -1989.000000 -1989.000000  ... -9.456106 -15.527955           0
10  3.0    -0.000318    -0.001604  ... -9.456106 -18.364787           0

[11 rows x 8 columns]

In [47]:
# Output print
import pandas as pd
FRAME_00_RESULTS_2 = pd.DataFrame(data = FRAME_00_RESULTS[2])
FRAME_00_RESULTS_2.head(50)

      X           UX           UY  ...          V          M  ID_ELEMENT
0   0.0     0.000002    -0.002808  ... -13.424818  20.841167           2
1   0.3 -1989.000000 -1989.000000  ... -13.424818  16.813722           2
2   0.6 -1989.000000 -1989.000000  ... -13.424818  12.786276           2
3   0.9 -1989.000000 -1989.000000  ... -13.424818   8.758831           2
4   1.2 -1989.000000 -1989.000000  ... -13.424818   4.731386           2
5   1.5 -1989.000000 -1989.000000  ... -13.424818   0.703940           2
6   1.8 -1989.000000 -1989.000000  ... -13.424818  -3.323505           2
7   2.1 -1989.000000 -1989.000000  ... -13.424818  -7.350951           2
8   2.4 -1989.000000 -1989.000000  ... -13.424818 -11.378396           2
9   2.7 -1989.000000 -1989.000000  ... -13.424818 -15.405841           2
10  3.0    -0.000454    -0.003608  ... -13.424818 -19.433287           2

[11 rows x 8 columns]

In [48]:
# Output print
import pandas as pd
FRAME_00_RESULTS_24 = pd.DataFrame(data = FRAME_00_RESULTS[24])
FRAME_00_RESULTS_24.head(50)

       X           UX           UY  ...          V          M  ID_ELEMENT
0   0.00    -0.000139    -0.013414  ... -35.301852  -1.270632          24
1   0.05 -1989.000000 -1989.000000  ... -35.301852  -3.035724          24
2   0.10 -1989.000000 -1989.000000  ... -35.301852  -4.800817          24
3   0.15 -1989.000000 -1989.000000  ... -35.301852  -6.565910          24
4   0.20 -1989.000000 -1989.000000  ... -35.301852  -8.331002          24
5   0.25 -1989.000000 -1989.000000  ... -35.301852 -10.096095          24
6   0.30 -1989.000000 -1989.000000  ... -35.301852 -11.861187          24
7   0.35 -1989.000000 -1989.000000  ... -35.301852 -13.626280          24
8   0.40 -1989.000000 -1989.000000  ... -35.301852 -15.391373          24
9   0.45 -1989.000000 -1989.000000  ... -35.301852 -17.156465          24
10  0.50    -0.000117    -0.006457  ... -35.301852 -18.921558          24

[11 rows x 8 columns]

In [50]:
# Output print
import pandas as pd
FRAME_00_RESULTS_35 = pd.DataFrame(data = FRAME_00_RESULTS[35])
FRAME_00_RESULTS_35.head(50)

       X           UX           UY  ...     V          M  ID_ELEMENT
0   0.00     0.000076    -0.006417  ... -45.0 -18.758101          35
1   0.05 -1989.000000 -1989.000000  ... -45.0 -21.008101          35
2   0.10 -1989.000000 -1989.000000  ... -45.0 -23.258101          35
3   0.15 -1989.000000 -1989.000000  ... -45.0 -25.508101          35
4   0.20 -1989.000000 -1989.000000  ... -45.0 -27.758101          35
5   0.25 -1989.000000 -1989.000000  ... -45.0 -30.008101          35
6   0.30 -1989.000000 -1989.000000  ... -45.0 -32.258101          35
7   0.35 -1989.000000 -1989.000000  ... -45.0 -34.508101          35
8   0.40 -1989.000000 -1989.000000  ... -45.0 -36.758101          35
9   0.45 -1989.000000 -1989.000000  ... -45.0 -39.008101          35
10  0.50     0.000094    -0.003234  ... -45.0 -41.258101          35

[11 rows x 8 columns]